name: Feature Branch CI

on:
  push:
    branches:
      - feature/*   # Trigger on feature branches

jobs:
  build:
    runs-on:
      - codebuild-myProject-${{ github.run_id }}-${{ github.run_attempt }}
        image: aws/codebuild/standard:5.0
        instance-size:small
        buildspec-override:true

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build project
        run: |
          echo "Running build on CodeBuild-hosted runner"
          npm install
          npm test

