name: Kube-Docker CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Detect package.json folder
        id: find_package
        run: |
          FILE=$(find . -name package.json | head -n 1)
          if [ -z "$FILE" ]; then
            echo "package.json not found! Exiting..."
            exit 1
          fi
          DIR=$(dirname "$FILE")
          echo "dir=$DIR" >> $GITHUB_OUTPUT

      - name: Install dependencies
        run: npm install
        working-directory: ${{ steps.find_package.outputs.dir }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Test AWS CLI
        run: aws sts get-caller-identity

      - name: Start AWS CodeBuild
        run: aws codebuild start-build --project-name kube-docker-build
